// Generated by CoffeeScript 1.3.3
var sendToMultiple, subscriptions;

subscriptions = require('./subscriptions');

module.exports = function(eventTransport, wsTransport, emitter) {
  return eventTransport.listen(function(obj) {
    var cb, send;
    send = wsTransport.event();
    cb = (function() {
      switch (obj.t) {
        case 'all':
          return function(msg) {
            return send.all(msg);
          };
        case 'socketId':
          return function(msg) {
            return send.socketId(obj.socketId, msg);
          };
        case 'channel':
          return function(msg) {
            return sendToMultiple(send, msg, obj.channels, 'channel');
          };
        case 'user':
          return function(msg) {
            return sendToMultiple(send, msg, obj.users, 'user');
          };
      }
    })();
    return emitter.emit('0', obj, {}, cb);
  });
};

sendToMultiple = function(send, msg, destinations, type) {
  destinations = destinations instanceof Array && destinations || [destinations];
  destinations.forEach(function(destination) {
    var data, excludeId, index, set, socketIds, socketIdsToSend;
    set = subscriptions[type];
    if (socketIds = set.members(destination)) {
      socketIdsToSend = socketIds.slice(0);
      if (msg.indexOf('exclude_id') >= 0) {
        data = JSON.parse(msg);
        excludeId = data.p[data.p.length - 1].exclude_id;
        index = socketIdsToSend.indexOf(excludeId);
        if (index >= 0) {
          socketIdsToSend.splice(index, 1);
        }
      }
      return socketIdsToSend.forEach(function(socketId) {
        if (!send.socketId(socketId, msg, destination)) {
          return set.removeFromAll(socketId);
        }
      });
    }
  });
  return true;
};
